import { GRID_INDENT, STAGE_WIDTH } from "./GeomStage";

export const FIGURE1 = {
  ID: 1,
  POINTS: [
    1 * GRID_INDENT, 11 * GRID_INDENT,
    1 * GRID_INDENT, 13 * GRID_INDENT,
    4 * GRID_INDENT, 13 * GRID_INDENT,
    4 * GRID_INDENT, 12 * GRID_INDENT,
    2 * GRID_INDENT, 12 * GRID_INDENT,
    2 * GRID_INDENT, 11 * GRID_INDENT
  ],
  TARGET_BOUNDS: [
    1 * GRID_INDENT, 11 * GRID_INDENT,
    1 * GRID_INDENT, 13 * GRID_INDENT,
    8 * GRID_INDENT, 13 * GRID_INDENT,
    8 * GRID_INDENT, 11 * GRID_INDENT
  ]
};

export const FIGURE2 = {
  ID: 2,
  POINTS: [
    STAGE_WIDTH - 4 * GRID_INDENT, 1 * GRID_INDENT,
    STAGE_WIDTH - 4 * GRID_INDENT, 2 * GRID_INDENT,
    STAGE_WIDTH - 2 * GRID_INDENT, 2 * GRID_INDENT,
    STAGE_WIDTH - 2 * GRID_INDENT, 3 * GRID_INDENT,
    STAGE_WIDTH - 1 * GRID_INDENT, 3 * GRID_INDENT,
    STAGE_WIDTH - 1 * GRID_INDENT, 1 * GRID_INDENT
  ],
  TARGET_BOUNDS: [
    STAGE_WIDTH - 5 * GRID_INDENT, 1 * GRID_INDENT,
    STAGE_WIDTH - 5 * GRID_INDENT, 3 * GRID_INDENT,
    STAGE_WIDTH + 2 * GRID_INDENT, 3 * GRID_INDENT,
    STAGE_WIDTH + 2 * GRID_INDENT, 1 * GRID_INDENT    
  ]
};

export const FIGURE3 = {
  ID: 3,
  POINTS: [
    STAGE_WIDTH - 4 * GRID_INDENT, 11 * GRID_INDENT,
    STAGE_WIDTH - 4 * GRID_INDENT, 13 * GRID_INDENT,
    STAGE_WIDTH - 1 * GRID_INDENT, 13 * GRID_INDENT,
    STAGE_WIDTH - 1 * GRID_INDENT, 11 * GRID_INDENT
  ],
  TARGET_BOUNDS: [
    STAGE_WIDTH - 4 * GRID_INDENT, 11 * GRID_INDENT,
    STAGE_WIDTH - 4 * GRID_INDENT, 13 * GRID_INDENT,
    STAGE_WIDTH + 3 * GRID_INDENT, 13 * GRID_INDENT,
    STAGE_WIDTH + 3 * GRID_INDENT, 11 * GRID_INDENT   
  ]
};
